import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  articles: defineTable({
    title: v.string(),
    body: v.string(),
    categoryId: v.id("categories"),
    topics: v.array(v.string()), // AI-generated topics for content grouping
    authorId: v.string(),
    imageStorageId: v.optional(v.id("_storage")), // Field for storing file storage ID
    // AI Processing System fields
    status: v.union(v.literal("draft"), v.literal("pending"), v.literal("approved"), v.literal("rejected")),
    isAutoGenerated: v.boolean(),
    isEdited: v.optional(v.boolean()),
    sourceUrls: v.array(v.string()),
    rssSourceOrigin: v.array(v.string()),
    viewCount: v.optional(v.number()),
    excerpt: v.optional(v.string()),
    slug: v.string(),
    imageGenPrompts: v.array(v.string()), // AI-generated image prompts for Midjourney/OpenAI
  })
  .index("by_category", ["categoryId"])
  .index("by_status", ["status"]),

  categories: defineTable({
    name: v.string(),
    slug: v.string(),
    keywords: v.optional(v.array(v.string())),
    isActive: v.optional(v.boolean()),
    createdAt: v.number(),
    updatedAt: v.optional(v.number()),
  }).index("by_slug", ["slug"]),

  topics: defineTable({
    name: v.string(),
    slug: v.string(),
    createdAt: v.number(),
  }).index("by_slug", ["slug"]),

  comments: defineTable({
    articleId: v.id("articles"),
    userId: v.string(),
    username: v.string(),
    avatarUrl: v.optional(v.string()),
    content: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
    isDeleted: v.boolean(),
  })
  .index("by_article", ["articleId"])
  .index("by_user", ["userId"]),

  rss_producer: defineTable({
    name: v.string(),
    url: v.string(),
    categoryId: v.id("categories"),
    isActive: v.boolean(),
    pollFrequency: v.number(),
    numberOfArticles: v.number(),
    lastPolled: v.optional(v.number()),
    nextRunTime: v.optional(v.number()),
    updatedAt: v.number(),
    // Run result fields
    lastRunSuccess: v.optional(v.boolean()),
    lastRunFeedStatus: v.optional(v.string()),
    lastRunCategoryStatus: v.optional(v.string()),
    lastRunArticlesFound: v.optional(v.number()),
    lastRunArticlesQueued: v.optional(v.number()),
    lastRunArticles: v.optional(v.array(v.object({
      title: v.string(),
      url: v.string(),
      publishedAt: v.string(),
      excerpt: v.string(),
    }))),
    lastRunError: v.optional(v.string()),
  })
  .index("by_category", ["categoryId"])
  .index("by_active", ["isActive"])
  .index("by_next_run", ["nextRunTime"]),

  rss_queue: defineTable({
    producerId: v.id("rss_producer"),
    title: v.string(),
    description: v.string(),
    url: v.string(),
    publishedAt: v.number(),
    processed: v.boolean(), // Keep for backward compatibility
    status: v.union(v.literal("waiting"), v.literal("processing"), v.literal("completed"), v.literal("failed")),
    categories: v.optional(v.array(v.string())),
    // AI Processing fields
    processedAt: v.optional(v.number()),
    errorMessage: v.optional(v.string()),
    retryCount: v.optional(v.number()),
    generatedArticleId: v.optional(v.id("articles")),
  })
  .index("by_producer", ["producerId"])
  .index("by_processed", ["processed"])
  .index("by_status", ["status"])
  .index("by_published", ["publishedAt"]),
});
