import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  articles: defineTable({
    title: v.string(),
    body: v.string(),
    categoryId: v.id("categories"),
    topics: v.array(v.string()), // AI-generated topics for content grouping
    authorId: v.string(),
    imageStorageId: v.optional(v.id("_storage")), // Field for storing file storage ID
    // AI Processing System fields
    status: v.union(v.literal("draft"), v.literal("pending"), v.literal("approved"), v.literal("rejected")),
    isAutoGenerated: v.boolean(),
    isEdited: v.optional(v.boolean()),
    sourceUrls: v.array(v.string()),
    rssSourceOrigin: v.array(v.string()),
    viewCount: v.optional(v.number()),
    excerpt: v.optional(v.string()),
    slug: v.string(),
    imageGenPrompts: v.array(v.string()), // AI-generated image prompts for Midjourney/OpenAI
  })
  .index("by_category", ["categoryId"])
  .index("by_status", ["status"]),

  categories: defineTable({
    name: v.string(),
    slug: v.string(),
    keywords: v.optional(v.array(v.string())),
    isActive: v.optional(v.boolean()),
    createdAt: v.number(),
    updatedAt: v.optional(v.number()),
  }).index("by_slug", ["slug"]),


  comments: defineTable({
    articleId: v.id("articles"),
    userId: v.string(),
    username: v.string(),
    avatarUrl: v.optional(v.string()),
    content: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
    isDeleted: v.boolean(),
  })
  .index("by_article", ["articleId"])
  .index("by_user", ["userId"]),

  rss_producer: defineTable({
    name: v.string(),
    url: v.string(),
    categoryId: v.id("categories"),
    isActive: v.boolean(),
    pollFrequency: v.number(),
    numberOfArticles: v.number(),
    lastPolled: v.optional(v.number()),
    nextRunTime: v.optional(v.number()),
    updatedAt: v.number(),
    // Run result fields
    lastRunSuccess: v.optional(v.boolean()),
    lastRunFeedStatus: v.optional(v.string()),
    lastRunCategoryStatus: v.optional(v.string()),
    lastRunArticlesFound: v.optional(v.number()),
    lastRunArticlesQueued: v.optional(v.number()),
    lastRunArticles: v.optional(v.array(v.object({
      title: v.string(),
      url: v.string(),
      publishedAt: v.string(),
      excerpt: v.string(),
    }))),
    lastRunError: v.optional(v.string()),
  })
  .index("by_category", ["categoryId"])
  .index("by_active", ["isActive"])
  .index("by_next_run", ["nextRunTime"]),

  rss_queue: defineTable({
    producerId: v.id("rss_producer"),
    title: v.string(),
    description: v.string(),
    url: v.string(),
    publishedAt: v.number(),
    processed: v.boolean(), // Keep for backward compatibility
    status: v.union(v.literal("waiting"), v.literal("processing"), v.literal("completed"), v.literal("failed")),
    categories: v.optional(v.array(v.string())),
    // AI Processing fields
    processedAt: v.optional(v.number()),
    errorMessage: v.optional(v.string()),
    retryCount: v.optional(v.number()),
    generatedArticleId: v.optional(v.id("articles")),
  })
  .index("by_producer", ["producerId"])
  .index("by_processed", ["processed"])
  .index("by_status", ["status"])
  .index("by_published", ["publishedAt"]),

  // Universal Create Queue (ADR 2) - Normalized queue for all content sources
  create_queue: defineTable({
    // Normalized fields - same for all source types
    title: v.string(),
    url: v.string(), 
    concept: v.string(), // Context for AI processing (RSS excerpt, research notes, YouTube transcript)
    category: v.string(), // Category name for processing
    
    // Source identification
    createSource: v.string(),
    
    // Processing workflow
    status: v.union(v.literal("pending"), v.literal("processing"), v.literal("complete")),
    queuedAt: v.number(),
    processedAt: v.optional(v.number()),
    isProcessing: v.boolean(),
    processed: v.boolean(),
    
    // AI Processing results
    generatedArticleId: v.optional(v.id("articles")),
    errorMessage: v.optional(v.string()),
    retryCount: v.optional(v.number()),
  })
  .index("by_status", ["status"])
  .index("by_processed", ["processed"])
  .index("by_queued_at", ["queuedAt"]),

  // Create workflow source tables
  create_rss: defineTable({
    name: v.string(),
    categoryId: v.id("categories"),
    // New fields (optional for backward compatibility)
    feedUrl: v.optional(v.string()),
    articlesInFeed: v.optional(v.number()), // Total number of articles found in the feed
    maxArticles: v.optional(v.number()), // Maximum articles to process
    matchedArticles: v.optional(v.array(v.object({
      title: v.string(),
      url: v.string(),
      description: v.string(),
      pubDate: v.string(),
    }))), // Articles that matched category keywords
    publishedAt: v.optional(v.string()),
    // Legacy fields (for backward compatibility)
    url: v.optional(v.string()),
    numberOfArticles: v.optional(v.number()),
    status: v.optional(v.union(v.literal("pending"), v.literal("processing"), v.literal("complete"))),
    lastPolled: v.optional(v.number()),
    nextRunTime: v.optional(v.number()),
    updatedAt: v.optional(v.number()),
    matched: v.optional(v.number()),
    // Common fields
    pollFrequency: v.number(),
    isActive: v.boolean(),
    createdBy: v.id("users"),
  })
  .index("by_category", ["categoryId"])
  .index("by_feed", ["feedUrl"]),

  create_research: defineTable({
    title: v.string(),
    concept: v.string(),
    status: v.union(v.literal("pending"), v.literal("processing"), v.literal("complete")),
    createdBy: v.id("users"),
    updatedAt: v.optional(v.number()),
  }),

  create_youtube: defineTable({
    videoUrl: v.string(),
    videoTitle: v.optional(v.string()),
    concept: v.string(),
    status: v.union(v.literal("pending"), v.literal("processing"), v.literal("complete")),
    duration: v.optional(v.number()),
    category: v.string(),
    timecodeStart: v.optional(v.number()),
    timecodeEnd: v.optional(v.number()),
    createdBy: v.id("users"),
    updatedAt: v.optional(v.number()),
  }),

  users: defineTable({
    clerkId: v.string(),
    username: v.optional(v.string()),
    updatedAt: v.optional(v.number()),
  }).index("by_clerk_id", ["clerkId"]),
});
